apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-applicationset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/BorisovCloud/gitops-demo.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: 'app-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/BorisovCloud/gitops-demo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'ns-{{path.basename}}'
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true